// ===== DOM-ELEMENT =====
const bradeEl       = document.getElementById('brade');
const statusTextEl  = document.getElementById('statusText');
const tankerEl      = document.getElementById('tankerIndikator');
const dragHistEl    = document.getElementById('dragHistorik');
const overKlockaEl  = document.getElementById('overKlocka');
const underKlockaEl = document.getElementById('underKlocka');
const overTagnaEl   = document.getElementById('overTagna');
const underTagnaEl  = document.getElementById('underTagna');
const overInfoEl    = document.getElementById('overSpelareInfo');
const underInfoEl   = document.getElementById('underSpelareInfo');
const overNamnEl    = document.getElementById('overSpelarnamn');
const underNamnEl   = document.getElementById('underSpelarnamn');
